#!/bin/bash

ret_code=0

/usr/bin/whoami | grep -q root
if [ $? -eq 0 ]; then
  # warning conditions

  # we disable zeroconf on servers
  /sbin/ip route show table all | grep -q 169.254 
  if [ $? -eq 0 ]; then
    ret_code=1
    echo 'WARNING: zeroconf network is enabled' 
  fi
  
  # check if /etc is a git repo
  git rev-parse --show-cdup &> /dev/null
  if [ $? -ne 0 ]; then
    ret_code=4
    echo "WARNING: /etc has not been properly initialized with etckeeper"
  fi

  # error conditions
  # double-check that sshd config is intact
  /usr/sbin/sshd -t 
  if [ $? -ne 0 ]; then
    ret_code=2
    echo 'ERROR: /etc/ssh/sshd_config is fubar'
  fi

  # check if we appear to have modified sshd_config
  for file in ssh_config sshd_config; do
    grep '^#BASELINE_START' /etc/ssh/$file &> /dev/null || echo "ERROR: $file is incomplete"
    grep '^#BASELINE_STOP'  /etc/ssh/$file &> /dev/null || echo "ERROR: $file is incomplete"
  done

  ## end of checks
else
  ret_code=2
  echo "ERROR: must be root"
fi

exit $ret_code
